FROM rust:1.72-alpine

WORKDIR /usr/src/warmer

RUN apk update; \
    apk upgrade;

RUN apk add --no-cache \
    python3 \
    python3-dev \
    musl-dev \
    openssl \
    openssl-dev \
    libudev-zero \
    build-base \
    libc-dev \
    pcc-libs-dev \
    pkgconfig \
    libc6-compat \
    gcompat \
    libxcb-dev \
    libxkbcommon-dev

COPY . .

RUN cargo -V && cargo build --release \
    && cp target/release/warmer /usr/bin/warmer

CMD ["/usr/bin/warmer"]